parameters:
    twig.extension.array.class: Acme\HelloBundle\Twig\Extension\ArrayExtension

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.array:
        class: %twig.extension.array.class%
        tags:
            - { name: twig.extension }
